const PromoImgs = [
  "/bts/promo/Promo-1.webp",
  "/bts/promo/Promo-2.webp",
  "/bts/promo/Promo-3.webp",
  "/bts/promo/Promo-4.webp",
  "/bts/promo/Promo-5.webp",
  "/bts/promo/Promo-6.webp",
  "/bts/promo/Promo-7.webp",
  "/bts/promo/Promo-8.webp",
  "/bts/promo/Promo-9.webp",
  "/bts/promo/Promo-10.webp",
  "/bts/promo/Promo-11.webp",
  "/bts/promo/Promo-12.webp",
  "/bts/promo/Promo-13.webp",
  "/bts/promo/Promo-14.webp",
  "/bts/promo/Promo-15.webp",
  "/bts/promo/Promo-16.webp",
  "/bts/promo/Promo-17.webp",
  "/bts/promo/Promo-18.webp",
  "/bts/promo/Promo-19.webp",
  "/bts/promo/Promo-20.webp",
  "/bts/promo/Promo-21.webp",
  "/bts/promo/Promo-22.webp",
  "/bts/promo/Promo-23.webp",
  "/bts/promo/Promo-24.webp",
  "/bts/promo/Promo-25.webp",
  "/bts/promo/Promo-26.webp",
  "/bts/promo/Promo-27.webp",
  "/bts/promo/Promo-28.webp",
  "/bts/promo/Promo-29.webp",
  "/bts/promo/Promo-30.webp",
  "/bts/promo/Promo-31.webp",
];

export default PromoImgs;
