const SugarImgs = [
  "/bts/sugar/Sugar-1.webp",
  "/bts/sugar/Sugar-2.webp",
  "/bts/sugar/Sugar-3.webp",
  "/bts/sugar/Sugar-4.webp",
  "/bts/sugar/Sugar-5.webp",
  "/bts/sugar/Sugar-6.webp",
  "/bts/sugar/Sugar-7.webp",
  "/bts/sugar/Sugar-8.webp",
  "/bts/sugar/Sugar-9.webp",
  "/bts/sugar/Sugar-10.webp",
  "/bts/sugar/Sugar-11.webp",
  "/bts/sugar/Sugar-12.webp",
  "/bts/sugar/Sugar-13.webp",
  "/bts/sugar/Sugar-14.webp",
  "/bts/sugar/Sugar-15.webp",
  "/bts/sugar/Sugar-16.webp",
  "/bts/sugar/Sugar-17.webp",
  "/bts/sugar/Sugar-18.webp",
  "/bts/sugar/Sugar-19.webp",
  "/bts/sugar/Sugar-20.webp",
  "/bts/sugar/Sugar-21.webp",
  "/bts/sugar/Sugar-22.webp",
  "/bts/sugar/Sugar-23.webp",
  "/bts/sugar/Sugar-24.webp",
  "/bts/sugar/Sugar-25.webp",
  "/bts/sugar/Sugar-26.webp",
  "/bts/sugar/Sugar-27.webp",
];

export default SugarImgs;
